### ISSUE TITLE
Can't run the project.

### ISSUE THREAD

**Issue by patrickpoh** [ggomaeng/react-native-card-modal#1]
Hey man! awesome stuff but I cant run the project even after i npm install everything. 

It gives me this error `(node:2424) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
(node:2424) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

ENOENT: no such file or directory, uv_chdir`

**Comment by ggomaeng** [comment]
Hey patrick! Let me check it out and get back to you. Sorry about that--first time actually sharing stuff with other people.

**Comment by patrickpoh** [comment]
hey park! No worries :)

**Comment by minhtc** [comment]
the iOS folder is missing, I thought so.

**Comment by ggomaeng** [comment]
Patrick, I think this has to do with the node version. This seems to be a common issue on node version 7.0.0. I used nvm to install the version 6.7.0 and it works! Give that a shot

**Comment by ggomaeng** [comment]
My github account has been having issues :( I couldn't push the iOS folder, but that shouldn't be the problem since it will get rebuilt if you run the command. Also, run `react-native link` after the npm install! I forgot to mention that. Let me know how it goes @patrickpoh!

**Comment by minhtc** [comment]
copy ios folder from an empty project, run `react-native link`, then the issue should be fixed

**Comment by ggomaeng** [comment]
added the ios folder!

**Comment by patrickpoh** [comment]
@ggomaeng   @minhtc  Yup it works! but i didnt downgrade my node version. 
I simply react-native init cardmodal, 
copy the ios folder. 
git clone your project. 
paste the ios folder into your project
npm install and react-native link
react-native run-ios

Thank you!!

**Comment by ggomaeng** [comment]
Sorry for the inconvenience!! Glad it worked. Thank you @minhtc for the help :)

**Comment by patrickpoh** [comment]
No worries! Awesome job! Keep up the good work :)  고맙습니다!

**Comment by vantoan123** [comment]
help me!
I not run project ???

![simulator screen shot - iphone x - 2019-01-02 at 15 00 18](https://user-images.githubusercontent.com/44179598/50629498-5eeeb700-0f6f-11e9-9be0-6c4a7f75aa3b.png)
