### ISSUE TITLE
Does not work on React Native 0.50

### ISSUE THREAD

**Issue by vvavepacket** [ggomaeng/react-native-card-modal#12]
I am now using React Native 0.50, and the Image can not contain any children components anymore. How do we fix this issue?

`The <Image> component cannot contain children. If you want to render content on top of the image, consider using absolute positioning.`

I can see on the **card-modal.js** file, we have an Animated.Image and there is an inside component

`{back}`

How do we solve this? Thank you.

**Comment by ogil7190** [comment]
close the tag without any child and it will work and try to find some logic for back!

**Comment by ggomaeng** [comment]
You could try using `<ImageBackground>` component instead of `<Image>`.
