### ISSUE TITLE
Possibility of this actually becoming a Lib?

### ISSUE THREAD

**Issue by Zazzzles** [ggomaeng/react-native-card-modal#14]
Really love this idea, you mentioned that you are planning to turn this into a lib - is that and android support still in the pipelines?

**Comment by ggomaeng** [comment]
Hi Zazzzles! It's most likely going to be a standalone project. This project isn't an ideal solution for transitioning scenes, and it's limited. Please check out libraries like https://github.com/IjzerenHein/react-native-magic-move and https://github.com/fram-x/FluidTransitions, which does the job, but better.
