### ISSUE TITLE
Unable to scroll after expanding the card

### ISSUE THREAD

**Issue by satvikmaker** [ggomaeng/react-native-card-modal#7]
I am trying this on my mobile phone.

Please check out the [video](https://www.youtube.com/watch?v=xGKU5MF_CIU)

**Issues found**
- After expanding the card, I am unable to scroll
- The description in the card is half-cut and I'm unable to scroll with-in the expanded card
- No way to come out of the expanded card, only way is to exit the app

I actually saw a warning which I don't see it anymore. I am really sorry, I couldn't capture it at that point of time. The warning was like - The top-most component should be...

**Comment by ggomaeng** [comment]
Hey bozzmob, disabling scroll was intentional. Also, the back button is actually scrollable--the touchable opacity is just too small to detect the touch events. Feel free to take a look at the source code and submit a pull request!

**Comment by satvikmaker** [comment]
Oh! Sure, I'll take a look at it and send a PR :) Thanks for the quick reply.

**Comment by ggomaeng** [comment]
No problem :-) have fun!
